version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sisand-sqlserver
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    networks:
      - sisand-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sisand-backend
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sisand-sqlserver;Database=SisandDB;User Id=sa;Password=YourPassword123;TrustServerCertificate=True;
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - sisand-network

networks:
  sisand-network:
    driver: bridge
